[workspace]
resolver = "3"
members = ["console", "gateway", "message", "lib/logging", "lib/plugin", "lib/pubsub", "lib/security", "lib/protocol", "lib/sdk", "plugins/demo", "test-server", "lib/loadbalance", "lib/cache", "cli", "aiway", "plugins/rewrite-path", "logg", "lib/alert"]
