[package]
name = "model-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
logging = { path = "../lib/logging" }
alert = { path = "../lib/alert" }
tokio = { version = "1", features = ["macros", "io-util", "bytes"] }
rocket = { version = "0.5", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }